export enum CriteriaOperator {
  EQUALS = 'EQUALS',
  GREATER_THAN = 'GREATER_THAN',
  GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
  LESS_THAN = 'LESS_THAN',
  REQUIRED = 'REQUIRED',
  BETWEEN = 'BETWEEN',
}
